import {
  Cake,
  Heart,
  Rocket,
  Presentation,
  PartyPopper,
  HeartHandshake,
  Sparkles,
  Zap,
  Briefcase,
  Smile,
  Crown,
  Coffee,
  Sun,
  MessageCircle,
  FileText,
  Mail,
  Hash,
  AtSign,
  Image as ImageIcon,
  Instagram,
  Facebook,
  Twitter,
  Linkedin,
  Music,
  Code2,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  cake: Cake,
  heart: Heart,
  rocket: Rocket,
  presentation: Presentation,
  'party-popper': PartyPopper,
  'heart-handshake': HeartHandshake,
  sparkles: Sparkles,
  zap: Zap,
  briefcase: Briefcase,
  smile: Smile,
  crown: Crown,
  coffee: Coffee,
  sun: Sun,
  'message-circle': MessageCircle,
  'file-text': FileText,
  mail: Mail,
  hash: Hash,
  'at-sign': AtSign,
  image: ImageIcon,
  instagram: Instagram,
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  music: Music,
  code: Code2,
};

export function Icon({ name, className }: { name: string; className?: string }) {
  const Cmp = ICON_MAP[name] || Sparkles;
  return <Cmp className={className} />;
}
