import type { EventCategoryInfo, PromptLibraryItem } from '@/types';

export const EVENT_CATEGORIES: EventCategoryInfo[] = [
  {
    id: 'birthday',
    label: 'Birthday Party',
    icon: 'cake',
    description: 'Milestone celebrations, kids parties, and themed birthday bashes',
    gradient: 'from-pink-500 to-rose-500',
    sampleImage: 'https://images.pexels.com/photos/25956380/pexels-photo-25956380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/25956380/pexels-photo-25956380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/1543762/pexels-photo-1543762.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7180713/pexels-photo-7180713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30142374/pexels-photo-30142374.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
  {
    id: 'wedding',
    label: 'Wedding',
    icon: 'heart',
    description: 'Ceremonies, receptions, engagements, and anniversary celebrations',
    gradient: 'from-amber-400 to-orange-500',
    sampleImage: 'https://images.pexels.com/photos/17315417/pexels-photo-17315417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/17315417/pexels-photo-17315417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/29040997/pexels-photo-29040997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/19024679/pexels-photo-19024679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32142686/pexels-photo-32142686.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
  {
    id: 'business-launch',
    label: 'Business Launch',
    icon: 'rocket',
    description: 'Product reveals, store openings, and brand activation events',
    gradient: 'from-blue-500 to-cyan-500',
    sampleImage: 'https://images.pexels.com/photos/26150617/pexels-photo-26150617.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/26150617/pexels-photo-26150617.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/25809231/pexels-photo-25809231.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/25809255/pexels-photo-25809255.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/29708240/pexels-photo-29708240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
  {
    id: 'conference',
    label: 'Conference',
    icon: 'presentation',
    description: 'Seminars, workshops, panels, and professional gatherings',
    gradient: 'from-teal-500 to-emerald-500',
    sampleImage: 'https://images.pexels.com/photos/9275222/pexels-photo-9275222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/9275222/pexels-photo-9275222.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/26202153/pexels-photo-26202153.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15325468/pexels-photo-15325468.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
  {
    id: 'party',
    label: 'Party',
    icon: 'party-popper',
    description: 'Night out, club nights, house parties, and celebrations',
    gradient: 'from-violet-500 to-fuchsia-500',
    sampleImage: 'https://images.pexels.com/photos/5192316/pexels-photo-5192316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/5192316/pexels-photo-5192316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/6173886/pexels-photo-6173886.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/6224614/pexels-photo-6224614.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5191740/pexels-photo-5191740.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
  {
    id: 'charity',
    label: 'Charity & Gala',
    icon: 'heart-handshake',
    description: 'Fundraisers, galas, community drives, and benefit events',
    gradient: 'from-emerald-500 to-green-600',
    sampleImage: 'https://images.pexels.com/photos/35327677/pexels-photo-35327677.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/35327677/pexels-photo-35327677.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/38585616/pexels-photo-38585616.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/6646870/pexels-photo-6646870.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16120239/pexels-photo-16120239.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
  },
];

export const PROMPT_LIBRARY: PromptLibraryItem[] = [
  {
    id: 'p1',
    title: 'Instagram Caption — Birthday Bash',
    category: 'birthday',
    contentType: 'social-caption',
    prompt: 'Write a fun, energetic Instagram caption for a birthday party. Include the birthday person\'s name, age milestone, and party theme. Use 2-3 relevant emojis and end with a strong call-to-action to RSVP.',
    description: 'High-energy caption perfect for milestone birthday posts on Instagram.',
    tags: ['instagram', 'birthday', 'caption', 'social-media'],
  },
  {
    id: 'p2',
    title: 'Elegant Wedding Invitation',
    category: 'wedding',
    contentType: 'invitation-text',
    prompt: 'Compose an elegant wedding invitation text. Include the couple\'s names, ceremony date, venue, and dress code. The tone should be romantic and refined. End with RSVP details.',
    description: 'Formal, romantic invitation wording for wedding stationery.',
    tags: ['wedding', 'invitation', 'elegant', 'formal'],
  },
  {
    id: 'p3',
    title: 'Product Launch Press Release',
    category: 'business-launch',
    contentType: 'event-description',
    prompt: 'Write a compelling product launch event description. Highlight the product name, key features, launch date, and what attendees will experience. Use a professional yet exciting tone.',
    description: 'Professional description for product reveals and business launches.',
    tags: ['business', 'launch', 'press', 'professional'],
  },
  {
    id: 'p4',
    title: 'TikTok Hook — Party Promo',
    category: 'party',
    contentType: 'social-caption',
    prompt: 'Create a viral-worthy TikTok caption and hook for a party promotion. The first line must grab attention in under 3 seconds. Include trending-style hashtags and a call to action.',
    description: 'Scroll-stopping caption designed for TikTok party promotion.',
    tags: ['tiktok', 'party', 'viral', 'hook'],
  },
  {
    id: 'p5',
    title: 'LinkedIn Event Announcement',
    category: 'conference',
    contentType: 'social-caption',
    prompt: 'Write a professional LinkedIn post announcing a conference or seminar. Include the event name, key speakers, date, location, and what professionals will gain from attending. Use a polished, industry-appropriate tone.',
    description: 'B2B-focused announcement for conferences and professional events.',
    tags: ['linkedin', 'conference', 'professional', 'b2b'],
  },
  {
    id: 'p6',
    title: 'Charity Gala Email Subject Lines',
    category: 'charity',
    contentType: 'email-subject',
    prompt: 'Generate 5 compelling email subject lines for a charity gala invitation. Each should be under 50 characters, evoke urgency or emotion, and drive open rates.',
    description: 'High-converting email subject lines for fundraising events.',
    tags: ['email', 'charity', 'subject-line', 'fundraiser'],
  },
  {
    id: 'p7',
    title: 'Event Hashtag Generator',
    category: 'custom',
    contentType: 'hashtag-set',
    prompt: 'Generate 15 relevant hashtags for an event. Mix branded, community, and trending tags. Avoid banned or spammy hashtags. Group them by: branded, event-type, location, and trending.',
    description: 'Strategic hashtag sets grouped by purpose for maximum reach.',
    tags: ['hashtags', 'reach', 'social-media', 'strategy'],
  },
  {
    id: 'p8',
    title: 'AI Image Prompt — Birthday Scene',
    category: 'birthday',
    contentType: 'image-prompt',
    prompt: 'Create a detailed AI image generation prompt for a birthday party scene. Specify lighting, color palette, composition style, mood, and key visual elements like balloons, cake, and decorations.',
    description: 'Rich visual prompt for AI image generators to create birthday imagery.',
    tags: ['image-prompt', 'birthday', 'ai-art', 'visual'],
  },
  {
    id: 'p9',
    title: 'AI Image Prompt — Wedding Aesthetic',
    category: 'wedding',
    contentType: 'image-prompt',
    prompt: 'Create a detailed AI image generation prompt for a wedding scene. Describe the venue ambiance, floral arrangements, lighting, color palette, and romantic atmosphere. Specify a photorealistic style.',
    description: 'Cinematic image prompt for generating wedding-themed visuals.',
    tags: ['image-prompt', 'wedding', 'ai-art', 'photorealistic'],
  },
  {
    id: 'p10',
    title: 'AI Image Prompt — Product Reveal',
    category: 'business-launch',
    contentType: 'image-prompt',
    prompt: 'Create a detailed AI image generation prompt for a product launch event. Describe a modern stage setup, dramatic lighting, sleek product display, and an audience in anticipation. Use a cinematic, high-tech aesthetic.',
    description: 'Tech-forward visual prompt for product launch imagery.',
    tags: ['image-prompt', 'business', 'launch', 'cinematic'],
  },
  {
    id: 'p11',
    title: 'Email Newsletter — Event Recap',
    category: 'conference',
    contentType: 'event-description',
    prompt: 'Write an event recap email for a conference. Summarize key highlights, top moments, speaker quotes, and next steps. Include a thank-you to attendees and a link to resources.',
    description: 'Post-event email that keeps attendees engaged after the conference.',
    tags: ['email', 'recap', 'conference', 'follow-up'],
  },
  {
    id: 'p12',
    title: 'Instagram Story Sequence',
    category: 'party',
    contentType: 'social-caption',
    prompt: 'Write a 5-slide Instagram Story sequence promoting a party. Each slide should have a short caption, a visual suggestion, and a sticker/interactive element idea. Build excitement from slide 1 to 5.',
    description: 'Multi-slide story plan with captions and visual direction.',
    tags: ['instagram', 'story', 'party', 'sequence'],
  },
];

export const TONE_OPTIONS = [
  { id: 'exciting', label: 'Exciting', icon: 'zap' },
  { id: 'elegant', label: 'Elegant', icon: 'sparkles' },
  { id: 'professional', label: 'Professional', icon: 'briefcase' },
  { id: 'playful', label: 'Playful', icon: 'smile' },
  { id: 'luxurious', label: 'Luxurious', icon: 'crown' },
  { id: 'casual', label: 'Casual', icon: 'coffee' },
  { id: 'inspirational', label: 'Inspirational', icon: 'sun' },
] as const;

export const PLATFORM_OPTIONS = [
  { id: 'instagram', label: 'Instagram', icon: 'instagram' },
  { id: 'facebook', label: 'Facebook', icon: 'facebook' },
  { id: 'twitter', label: 'Twitter / X', icon: 'twitter' },
  { id: 'linkedin', label: 'LinkedIn', icon: 'linkedin' },
  { id: 'tiktok', label: 'TikTok', icon: 'music' },
  { id: 'email', label: 'Email', icon: 'mail' },
] as const;

export const CONTENT_TYPE_OPTIONS = [
  { id: 'social-caption', label: 'Social Media Caption', icon: 'message-circle', description: 'Catchy captions for posts and stories' },
  { id: 'event-description', label: 'Event Description', icon: 'file-text', description: 'Full-length description for listings and pages' },
  { id: 'invitation-text', label: 'Invitation Text', icon: 'mail', description: 'Formal or casual invitation wording' },
  { id: 'hashtag-set', label: 'Hashtag Set', icon: 'hash', description: 'Strategic hashtags grouped by purpose' },
  { id: 'email-subject', label: 'Email Subject Lines', icon: 'at-sign', description: 'High open-rate subject line options' },
  { id: 'email-body', label: 'Email Body', icon: 'mail', description: 'Full email copy for invitations & newsletters' },
  { id: 'email-invitation', label: 'Email Invitation', icon: 'mail', description: 'Complete invitation email with subject & body' },
  { id: 'email-reminder', label: 'Email Reminder', icon: 'bell', description: 'Pre-event reminder email to confirmed guests' },
  { id: 'email-followup', label: 'Email Follow-Up', icon: 'corner-up-left', description: 'Post-event thank you & recap email' },
  { id: 'image-prompt', label: 'AI Image Prompt', icon: 'image', description: 'Detailed prompt for AI image generators' },
  { id: 'code-snippet', label: 'Code Snippet', icon: 'code', description: 'RSVP pages, countdowns & event code' },
] as const;
